machine_type    =   "e2-micro"
name            =   "jenkins-server"
project         =   "nice-proposal-229011"
zone            =   "us-central1-a"
region          =   "us-central1"
image_name      =   "ubuntu-1804-bionic-v20210817"
image_project    =   "ubuntu-os-cloud"